angulartics/angulartics2

.npmignore
README.md
index.ts
karma-test-shim.js
karma.conf.js
package.json
src/core/angulartics2.spec.ts
src/core/angulartics2.ts
src/core/angulartics2On.spec.ts
src/index.ts
src/providers/angulartics2-google-analytics.spec.ts
src/providers/angulartics2-google-analytics.ts
src/providers/angulartics2-kissmetrics.spec.ts
src/providers/angulartics2-kissmetrics.ts
src/providers/angulartics2-mixpanel.spec.ts
src/providers/angulartics2-mixpanel.ts
src/providers/angulartics2-segment.spec.ts
src/providers/angulartics2-segment.ts
src/test.mocks.ts
tsconfig.json
typings.json

closes https://github.com/angulartics/angulartics2/issues/9
The following would have been done in separate PR but it needed it all:
* Update to beta.11
* Using `typings` to manage typings
* Simplified npm setup
* Tighter testing setup and verified tests 100% (*some previous tests did not work actually*)

fix(Window): removes implicit dependency on window

---

.npmignore

This will get rid of unnecessary files when users `npm install` this plugin.
Please merge and then republish following this *very important*:
https://github.com/angulartics/angulartics2/issues/15

chore: npm cleanup

---

tsconfig.json

closes https://github.com/angulartics/angulartics2/issues/17

fix(npm): fix tsconfig

---

src/core/angulartics2.ts

This would help me keeping DRY with the workaround on https://github.com/angulartics/angulartics2/issues/29#issuecomment-220213585

Expose service methods for inherited classes

---

src/providers/angulartics2-piwik.ts

closes https://github.com/angulartics/angulartics2/issues/44

fix(provider): Addresses _paq ReferenceError 

---

src/providers/angulartics2-google-analytics.ts

Added additional check for _gac
Fixes https://github.com/angulartics/angulartics2/issues/11

fix(analytics): _gaq is undefined

---

README.md

add
- event label
- the way to track events in the code

add event label and the way to track events in the code

---

package.json
src/providers/gtm/angulartics2-gtm.spec.ts
src/providers/gtm/angulartics2-gtm.ts
src/providers/index.ts

Here is the provider for GTM.  Welcoming feedback or modifications.  Tests are included.

Google Tag Manager

---

README.md
package.json
src/providers/hubspot/angulartics2-hubspot.spec.ts
src/providers/hubspot/angulartics2-hubspot.ts
src/providers/index.ts

Hubspot Provider 
Hubspot Javascript API Reference
http://developers.hubspot.com/docs/methods/tracking_code_api/tracking_code_overview

Hubspot Provider

---

src/providers/ga/angulartics2-ga.ts

Fixes https://github.com/angulartics/angulartics2/issues/108

Reset custom dimensions and metrics

---

src/providers/piwik/angulartics2-piwik.ts

See https://github.com/angulartics/angulartics2/issues/151

Add Logout-Support for Piwik

---

README.md
src/providers/index.ts
src/providers/intercom/angulartics2-intercom.spec.ts
src/providers/intercom/angulartics2-intercom.ts
yarn.lock

Add Intercom.com tracking provider support with page tracking, event tracking and user
identification
feature
Currently Intercom is not supported
Add Intercom.com tracking provider support with page tracking, event tracking and user
identification

feat(provider): Add Intercom tracking provider support

---

.github/CONTRIBUTING.md

fix(docs) typos in CONTRIBUTING doc.

---

src/lib/providers/piwik/README.md

docs: add piwik configuration documentation #120

---

README.md
src/lib/providers/clicky/README.md

Documentation for Clicky provider.
No docs for clicky.
Docs for clicky.

docs: initial clicky documentation

---

build.ts
src/lib/core/angulartics2.ts
src/lib/providers/appinsights/angulartics2-appinsights.ts

fix(providers): rxjs lettable operators import fix #190

---

src/lib/core/angulartics2On.spec.ts
src/lib/core/angulartics2On.ts

Better Angular Universal support

feat(core): refactor: use Renderer2 service instead of EventManager

---

README.md

None, only a readme change
The link in the Readme doesn't work
Now it does!
😄

Typo in link

---

src/lib/providers/segment/README.md

Adds instructions for setting up Segment
There are no instructions
There are instructions :)
It's just text

Add setup instructions for Segment

---

src/lib/providers/baidu/angulartics2-baidu.spec.ts
src/lib/providers/baidu/angulartics2-baidu.ts

1. Fix: Outdated Baidu analytics provider variable. Use `_hmt` instead of `hmt`.
2. Fix: Correct the typo: `_ setAutoPageview` => `_setAutoPageview`
3. Update test scripts.
#205 

feat(provider): Baidu Analytics Provider Is Outdated #205

---

src/lib/providers/mixpanel/README.md

Docs
No information on Setup
Brief setup section
n/a

Update Mixpanel README

---

src/lib/core/angular-router.ts

fix(core): add delay to router events to catch title #112

---

src/lib/providers/facebook/README.md

Instructions on how to setup Facebook Pixel similar to what exists for Google Analytics

Setup instructions for Facebook Pixel

---

README.md

- more structure
- some more information in headlines
- fixed some typos
- empty lines added for code readability
- crosslink for no-router and ui-router in installation instructions
- removed duplicated Google Analytics instructions with link(s)

Random changes to README

---

README.md
src/lib/core/angulartics2-config.ts
src/lib/core/angulartics2.spec.ts
src/lib/core/angulartics2.ts

A new flag to change tracking behavior
No way to remove hashes from url
Ability to remove hashes from the url

feat: flag to remove hashes (#) from url path

---

src/lib/core/angulartics2-config.ts
src/lib/providers/ga/angulartics2-ga.spec.ts
src/lib/providers/ga/angulartics2-ga.ts

Added anonymizeIP option to Google Analytics provider
closes #250

feat(provider): GA anonymizeIP

---

src/lib/providers/mixpanel/README.md

Update README.md for mixpanel
Lack of detailed integration.
Added code to integrate mixpanel with NgRx, also with a common error.

docs: Update README.md for mixpanel

---

src/lib/providers/gst/README.md

Update the Google Site Tag README.
Fix links, update setup code, markdownlint

docs: Update GST docs to v7

---

src/lib/providers/gtm/gtm.ts

- added ability to push custom data layer
- cleanup and remove repeated code

fix(GTM): Ability to push absolutely custom data layer

---

README.md

Love the work you’ve done here. At Segment, we recently released an Angular quickstart guide allowing developers to get setup easily and send data to 250+ destinations. We’d love to have an intro to our guide at the bottom of your README. Cheers!

Release of Segment Angular Quickstart Guide

---

src/lib/providers/splunk/README.md

The previous header import statement represented mixpanel - updated to splunk
Documentation correction

Corrected Splunk import statement

---

README.md

docs: Added Pyze provider to the README

---

README.md

docs: update README file with new provider option
