src/providers/gtm/angulartics2-gtm.spec.ts, src/providers/gtm/angulartics2-gtm.ts
Bug Fix
Issue is Event Tracking using the GTM provider does not send the label to the dataLayer - more can be seen here: #22 
Event Label is correctly sent to the dataLayer
Event label was being passed to GTM on line 63, the code read:
```javascript 
targetProperties: properties.label,
```
When it should have been:
```javascript 
label: properties.label,
```
=> Update to angulartics2-gtm.ts to fix Event Labels

src/providers/ga/angulartics2-ga.spec.ts, src/providers/ga/angulartics2-ga.ts
The exceptionTrack method in Angular2GoogleAnalytics was checking for three fields that were not
used anywhere in the method. Removed them. Also corrected the unit test for this method
appropriately.
Issue #95
=> fix(provider): removed erroneous validation from exceptionTrack

README.md, package.json, src/providers/adobeanalytics/angulartics2-adobeanalytics.spec.ts, src/providers/adobeanalytics/angulartics2-adobeanalytics.ts, src/providers/index.ts
Adds provider for Adobe Analytics that supports page and event tracking.
Adobe Analytics not currently supported #110 
Adobe Analytics support.
=> Add Adobe Analytics (Omniture) Provider

src/providers/hubspot/angulartics2-hubspot.ts
I added this because when I was running tests on my local app without having a global variable loading the plugin would break tests.  Instead of requiring app writers to worry about this, it makes more sense to add undefined checks here.
Bug Fix
Fixes tests on other apps that use this plugin
=> Update Hubspot plugin to undefined check global variable

src/core/angulartics2On.spec.ts, src/core/angulartics2On.ts
Bug fixes
When running on server there are no DOM elements. And this error occurs: `TypeError: element.addEventListener is not a function`
Do not bind the events when running on server-side.
=> Do not bind event running on server-side

src/providers/ga/angulartics2-ga.spec.ts, src/providers/ga/angulartics2-ga.ts
feature
hitCallback property is ignored, see see: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#hitCallback
hitCallback property is taken into account, this allows tracking of outbound links, see https://support.google.com/analytics/answer/1136920?hl=en
functionallity fully tested, impatient people can use this tarball: https://github.com/JohannesHoppe/angulartics2/releases/tag/v.2.2.3-fork
=> feat(provider): hitCallback function for ga

src/index.ts
OpaqueToken is removed in angular 5. InjectionToken was added in v4.0.0. Switch asap!
https://angular.io/api/core/OpaqueToken
https://angular.io/api/core/InjectionToken
=> fix(core) OpaqueToken deprecated, use InjectionToken

src/providers/adobeanalytics/angulartics2-adobeanalytics.ts
Bug fix
If you try to set the user properties before 's' has been async loaded, it throws and exception that 's' is not defined.
The new behavior checks if 's' is available.
=> Fixed "ReferenceError: s is not defined"

src/providers/piwik/angulartics2-piwik.spec.ts, src/providers/piwik/angulartics2-piwik.ts
feature
#135
* (almost) fully downward compatible: setUserProperties still sets a custom variable as long as no property has a key like dimension{number}, like dimension12
* if properties contains at least one key like dimension{number}, all those are set as custom dimensions, any other keys are ignored
=> feat(provider): add custom dimensions support to piwik

package.json, tsconfig.es2015.json, tsconfig.es5.json, tsconfig.json
* Bug fix
* Output JS is using `es2015` module syntax
* Output JS is using `commonjs` module syntax
* Couldn't use angulartics2 using Angular Universal in `node` when output JS is using `es2015` module syntax
=> build(dist): Build es5 and es2015 output versions

README.md, src/core/angulartics2.spec.ts, src/core/angulartics2.ts
Bug fix
https://github.com/angulartics/angulartics2/issues/147
Now the `excludeRoutes` method defined in the `Angulartics2` accepts an array of both string literals and RegExp values.
=> Issue 147 fix

src/lib/core/angulartics2.ts, src/lib/core/package.json, src/lib/providers/appinsights/angulartics2-appinsights.ts, src/lib/providers/piwik/angulartics2-piwik.ts
This brings rxjs minimum version to ^5.5.0
More information on why lettable operators https://github.com/ReactiveX/rxjs/blob/6dc1b807fe0c60314cbf008655ce395bc2d6ed9b/doc/lettable-operators.md
I've added types to the ReplaySubjects. Already seeing some get a bit confusing without type strictness.
```ts
setUsername = new ReplaySubject<{userId: string | number} | string>(10);
```
=> perf(core): rxjs lettable operators, types on replay subjects

src/providers/gtm/angulartics2-gtm.spec.ts, src/providers/gtm/angulartics2-gtm.ts
New feature - allow custom tags as part of the GTM provider. New gtmCustom property.
closes https://github.com/angulartics/angulartics2/issues/162
=> feat(provider) GTM - add custom tag ability

src/core/angulartics2.spec.ts, src/core/angulartics2.ts
Added an option that clears all numeric ids from the route to be able to reliably track urls with
changing ids.
URLs from page tracking can now be cleared of included IDs, which can intercept proper tracking on applications like a control panel in which every user has different ids in his url.
All URLs are being being tracked as they are. This can become an issue if every user has, for example, their own project, which results in URLs like `/project/12981/feature` with a different number for every user, which is being documented as a different pages.
If the setting …
=> feat(core): Added option to clear ids from url

build.ts, src/lib/core/angulartics2-config.ts, src/lib/core/angulartics2-token.ts, src/lib/core/angulartics2.module.ts, src/lib/core/angulartics2.spec.ts, src/lib/core/angulartics2.ts, src/lib/core/public_api.ts, src/lib/providers/adobeanalytics/angulartics2-adobeanalytics.ts, src/lib/providers/appinsights/angulartics2-appinsights.ts, src/lib/providers/facebook/angulartics2-facebook.ts, src/lib/providers/ga/angulartics2-ga.spec.ts, src/lib/providers/ga/angulartics2-ga.ts, src/lib/providers/gtm/angulartics2-gtm.ts
before settings could only be set after importing inside another service or component.
now settings can be set on app init with type checking.
```ts
Angulartics2Module.forRoot([Angulartics2GoogleAnalytics], { 
developerMode: true,
excludedRoutes: ['/abc'],
});
```
adds deprecated flags to the config setter functions like virtualPageviews as its pretty straight forward to set them using settings or the same way the rest the settings are done.
=> feat(core): allow settings from forRoot

src/lib/core/angulartics2.module.ts
Removes module import protection so lazy modules import work
There is no way you can use `Angulartics2On` directive in lazy modules
It is expected to import `Angulartics2Module` in any lazy module, to use `Angulartics2On`
The way the import protection was implemented does not allow
the `Angulartics2Module` to be imported in lazy loaded modules,
however this is required in order to use `Angulartics2On` directive
in there.
To shortly disambiguate usage of `forRoot()` and similar protection:
- Such protection is need mainly to not allow providers that are meant
to be global …
=> fix(core): remove module import protection so lazy modules import work

src/app/app.component.ts
The documentation is missing `/ga` for the "Import all providers in
root component" section of https://angulartics.github.io/angulartics2/#getting-started
Update to the documentation/ghpages website.
Line is updated to `import { Angulartics2GoogleAnalytics } from 'angulartics2/ga';`
=> docs: Update component import in Getting Started for ga example

src/lib/providers/ga/angulartics2-ga.ts
Uses typeof checks everwhere (as used by eventTrack) to prevent 
```
ReferenceError: ga is not defined
at Angulartics2GoogleAnalytics.setDimensionsAndMetrics (angulartics2-ga.js:163)
at Angulartics2GoogleAnalytics.setUserProperties (angulartics2-ga.js:160)
```
for users with tracking blockers.
It throws an error if adblockers are used and the site uses setUserProperties.
It doesn't throw.
I really like this module!
=> fix(providers): Don't throw if ga is not defined

src/lib/providers/ga/angulartics2-ga.ts
It optimizes the set and reset of custom dimensions and metrics in google analytics
The code loops from 0 to 200 and sets all unused dimensions to undefined, same thing with metrics.  I assume this is to reset custom dimensions from a previous call.
This generates ~400 calls to ga('set', 'dimension-n', undefined) per each event that you want to track.
This takes between 2ms and 6 ms per event in a highspeed conection, if you want to track several events under a mobile connection it gets really slow.
Instead of the looping from 0 to 200, the code caches setting custom dimensions and metrics and on next …
=> fix(providers): GA optimized reset of custom dimensions and metrics

src/lib/providers/gtm/angulartics2-gtm.ts
Allows to extend Angulartics2GoogleTagManager class and use this.angulartics2 within overriden methods.
Changing accessibility of `angulartics2` field in Angulartics2GoogleTagManager 
* **What is the current behavior?**
When extending `Angulartics2GoogleTagManager` and overriding for instance the `pageTrack(path: string)` method, you're not able to use this.angulartics2 field, as it is private in the super class.
When extending the Angulartics2GoogleTagManager class, you're able to access the injected angulartics field.
Other providers have the same issue. If you agree and it makes sense to change those as well, I can change it in those providers too …
=> fix(providers): Change accessibility of angulartics2 field in Angulartics2GoogleTagManager provider

src/lib/providers/ga/angulartics2-ga.spec.ts, src/lib/providers/ga/angulartics2-ga.ts
Similar to tracking pageviews and events, custom dimensions and metrics are applied to all additional account names.
The current behaviour only adds custom dimensions and metrics to the unnamed tracker. #119 
Custom dimensions and metrics are added to all account names supplied by the user.
I cannot run the build locally, assumably a Windows issue. However I have been able to run the tests and see them pass.
=> Add dimensions and metrics to all account names

README.md, src/lib/core/angulartics2-config.ts, src/lib/core/angulartics2.spec.ts, src/lib/core/angulartics2.ts, src/lib/test.mocks.ts
… added query params clearing
It is now possible via configuration to clear QueryParams alone, and set the RegExp used to clear
url parts. By default the clearUrl function now remove pure ids (only number) and UUIDs, and not
anything having a number in it
fix #204
=> feat(core): clearUrl - New RegExp for url clearing, new configuration options

src/lib/providers/ga/angulartics2-ga.spec.ts, src/lib/providers/ga/angulartics2-ga.ts
It properly manages GA when tracker name is defined, i.e. when angulartics2.settings.ga.additionalAccountNames is set.
When GA tracker name is set, all calls to `ga()` require to prefix command with tracker name.
See https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers, especially
> To send pageviews for the above two trackers, you'd run the following two commands:
```
ga('send', 'pageview');
ga('clientTracker.send', 'pageview');
```
`angulartics2-ga.js` is partially taking into account angulartics2.settings.ga.additionalAccountNames, typically on:
* `angulartics2-ga.eventTrack(action, properties)` - but not for ga('set', '&uid', userId)
* `angulartics2-ga.pageTrack(path)`
The missing places where 'accountName' is now managed
* …
=> feat(provider): GA - take into account "tracker" in all cases

README.md, src/lib/providers/ga/README.md, src/lib/providers/gtm/README.md
Added some note and links to make clearer that gtag.js (which Google Analytics now pushes by default) is actually Google Tag Manager.
fixes #225
=> Make it easier to differentiate analytics.js and gtag.js

src/lib/providers/hubspot/angulartics2-hubspot.ts
Don't try to assign / initialize _hsq window object if it doesn't exist. This can cause errors in applications. (`ReferenceError: _hsq is not defined`)
the _gaq and ga objects are not initialized in this way in the google analytics integration.
This removes the code attempting to initialize the value of _hsq to an empty array if the type is undefined.
Currently, in some environments where adblock or other means are used to prevent hubspot loading, _hsq does not exist. Trying to assign a value to this variable throws an error (`ReferenceError: _hsq is not defined`)
if _hsq does not exist, it will not be …
=> fix(providers): HubSpot - Don't initialize _hsq object

build.ts
ibm-digital-analytics was missing from the build list so it was not being build and is missing from the npm package.
ibm-digital-analytics is missing from the npm package
ibm-digital-analytics is now part of the build list and will be added to the npm package on next build
=> fix: Added ibm-digital-analytics to build list

README.md, build.ts, src/app/providers/providers.component.ts, src/lib/core/angulartics2-config.ts, src/lib/providers/gst/README.md, src/lib/providers/gst/gst.spec.ts, src/lib/providers/gst/gst.ts, src/lib/providers/gst/package.json
New provider to support Google Analytics new default tracker Global Site Tag
#272 #155
Replica of the GTM module sans the `userID` method. Supports Page View, Custom Events and Exceptions.
=> feat: Google Global Site Tag

src/lib/providers/ga/README.md
This fixes some documentation. Link 3 referenced a step on the `next` branch, which is not an available method on the `master` branch
Current behavior on `master` branch references a link on `next` branch
Reference `master` branch
=> docs: Corrected "Setup Angulartics" link

src/lib/providers/gst/gst.spec.ts, src/lib/providers/gst/gst.ts
Fixes a bug where tracking blockers and asynchronous site tag loading could cause an Angular-crashing error
As described in #298, `ga.getAll` is run even when Analytics isn't loaded in, which can happen if the user has a tracking blocker installed or the script is just running slow.
Uses the documented wrapper from Google to ensure the code is run after GA is loaded.
=> fix(gst): Ensure GST is loaded in before running ga.getAll

src/lib/providers/piwik/piwik.spec.ts, src/lib/providers/piwik/piwik.ts
Add support for tracking site search requests using Piwik provider.
No support for trackSiteSearch event.
Site search request can be tracked using eventTrack.
=> feat: add trackSiteSearch event to Piwik provider

src/lib/providers/launch/README.md, src/lib/providers/launch/launch.spec.ts, src/lib/providers/launch/launch.ts, src/lib/providers/launch/package.json
Added a provider for the recent Tag Managemener Launch, by Adobe
No provider available for Launch, by Adobe
Provider for Launch, by Adobe, can handle pageTrack and eventTrack.
=> feat: add provider Launch, by Adobe

src/lib/providers/gtm/gtm.ts
The last change created an error while rendering an app using server-side rendering
```
ERROR ReferenceError: dataLayer is not defined
at Angulartics2GoogleTagManager.pushLayer
```
This caused the error
```
if (typeof dataLayer === 'undefined' && !dataLayer) {
return;
}
```
On the server, data layer is undefined (first condition true) so the second gives an error
=> fix(GTM): Fixed error given by data layer server-side

src/lib/providers/launch/launch.spec.ts, src/lib/providers/launch/launch.ts
Send Properties to Launch on pageTrack
Currently, only eventTrack sends properties
Send Properties to Launch on pageTrack
=> fix(launch): Send Properties to Launch on pageTrack

src/lib/providers/gst/gst-interfaces.ts, src/lib/providers/gst/gst.spec.ts, src/lib/providers/gst/gst.ts
A new feature into GST provider - user timings, [related docs](https://developers.google.com/analytics/devguides/collection/gtagjs/user-timings) 
User timings API is completely missing in GST
=> feat(GST): Implement user timings

.gitignore, src/lib/core/angulartics2-config.ts, src/lib/providers/gst/README.md, src/lib/providers/gst/gst-interfaces.ts, src/lib/providers/gst/gst.spec.ts, src/lib/providers/gst/gst.ts
This PR increase the GST provider support.
- Add support for setUsername and setUserProperties
- Add page_location on pageTrack because this seems logical
- Add interface for gst Event properties
- Add support for anonimyzeIp
- Add security check if tracking ID is duplicated in HTML and forRoot config
- Extends documentation accordingly
- Support for custom_map
Mostly linked to #273 #155
Multiple setUserProperties will be merge together, instead of using only the most recent one:
```
this.angulartics2.setUserProperties.next({ page_language: 'en_us' });
this.angulartics2.setUserProperties.next({ user_type: 'member' });
this.angulartics2.setUserProperties.next({ page_language: 'en_gb' });
```
will result in `{page_langue: 'en_gb', user_type: 'member'}` being sent with all later event/page …
=> feat(GST): GST provider larger support

src/lib/providers/ga/ga.ts
GA provider for analytics.js implementations has a (what appears to be long standing) bug that doesn't correctly pass the "transport" option to GA.
When transport is set to "beacon" the resulting hit is still sent using an image by default.
When transport is set to "beacon" eventTrack() now correctly uses analytics.js' support for navigator.sendBeacon().
The core of the problem seems to be an incorrect use of the GA API. 
The ga.send() function only accepts a single fieldsObject: https://developers.google.com/analytics/devguides/collection/analyticsjs/tracker-object-reference#send
Demonstration of the underlying issue: …
=> feat(ga): transport for event tracking

src/lib/core/angulartics2-core.ts, src/lib/providers/segment/segment.spec.ts, src/lib/providers/segment/segment.ts
From Segment docs:
"Note: The user data will remain cached until you explicitly clear the browser cache or call reset.
So don’t forget to call reset upon user log out!"
When you call `identity` in segment it stores the user data in local storage.
Segment provides a `reset` method to call to clear this data.
This PR introduces a way of calling `reset`.
- **What is the current behavior?**
There is currently no way to call `reset` and clear the users identity. 
Allows for clearing the users identity.
=> feat(segment): allow segment identity to be cleared

README.md
The current version doesn't include in the Readme the updated mapping for NG 13, and NG12. This fixes it.
Note that there is already a PR #441  open with the same idea, but the `latest` of Angulartics **does not work with ng12**.
Documentation
If installing latest version with `npm` on an Angular v12 the project fails because the version is unsupported.
This Documentation change updates the table to the correct version mapping
=> docs: updates readme to include correct ng support mapping

src/lib/package.json, src/lib/providers/pyze/pyze.spec.ts, src/lib/providers/pyze/pyze.ts
Updated deprecated profile API's
setUsername, setUserProperties are pointing to old profile API's
setUsername, setUserProperties are pointed to new profile API's
=> feat(Pyze): updated profile api's

src/lib/providers/pyze/pyze.ts
This fixes the type variable for update_profile_api
Update profile api type was -> string
updated string to any
=> fix(Pyze) : update_profile_api_type_fix

src/lib/providers/matomo/matomo.ts
Fix typings for Matomo :
- dimensions start form 1 and the maximum is 15 https://matomo.org/faq/reporting-tools/create-track-and-manage-custom-dimensions/
- the `value` of `eventTrack` is actually optional (as seen in the implementation)
- the current definition of `setUserProperties` prevents to define dimensions
```js
this.setUserProperties({
dimension1: this.appConfig.appCode,
});
```
>   Argument of type '{ dimension1: string; }' is not assignable to parameter of type 'SetCustomVariableMatomoProperties'.
Type '{ dimension1: string; }' is missing the following properties from type 'SetCustomVariableMatomoProperties': index, name, value, scope
=> fix(Matomo): typings and number of dimensions

src/lib/providers/posthog/posthog.spec.ts, src/lib/providers/posthog/posthog.ts
Adds a new option on Posthog provider.
No current behavior.
Users are able to set a group properties via Posthog provider.
=> feat(posthog): add option to set a group
